import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className='page_wrapper'>
          {/* Navbar */}
          <nav>
            <h1>RD2L</h1>
            <Link href='/' className=''>
              Main
            </Link>
            <Link href='/' className=''>
              Divisions
            </Link>
            <Link href='/' className=''>
              Login
            </Link>
          </nav>
          {/* Main content */}
          {children}
          {/* Footer */}
          <footer>
            <div>
              <h1>Contact</h1>
                <ul className="dataList">
                  <li>Join Discord</li>
                  <li>Email</li>
                  <li>Report a bug</li>
                  <li>Provide Feedback</li>
                </ul>
            </div>
            <div>
              <h1>Resources</h1>
                <ul className="dataList">
                  <li>League Rules</li>
                  <li>Inhouse Rules</li>
                  <li>Playoff Bracket</li>
                </ul>
            </div>
            <div>
              <h1>Built Using</h1>
                <ul className="dataList">
                  <li>Next JS</li>
                  <li></li>
                  <li></li>
                </ul>
            </div>
            <div className="social">
              <ul className="dataList">
                <li>Twitch</li>
                <li>Github</li>
                <li>Discord</li>
              </ul>
            </div>
            <div className='legalStuff'>
              <p>All product and company names are trademarks™ or registered® trademarks of their respective holders. Use of them does not imply any affiliation with or endorsement by them.</p>
            </div>
          </footer>
        </div>
      </body>
    </html>
  )
}
