import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SessionWrapper from '@/components/sessionWrapper'
import NavBar from '@/components/navBarMenu'
import FooterMenu from '@/components/footerMenu'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body>
          <NavBar/>
          {children}
          <FooterMenu/>
        </body>
      </html>
    </SessionWrapper>
  )
}
